conf/apel_rest_api.conf
conf/ssl.conf

SSLVerifyClient switched to optional because otherwise when using tokens to access summaries you still need a X.509 certificate to connect to the server
Pass token to underlying Django server (not sure why this is needed now / how it was ommited before!)

Auth bug fix

---

apel_rest/settings.py

- rather than linking it to a particular instance in kubernetes `/accounting-server/` referred to its deployment on https://indigo-paas.cloud.ba.infn.it/, doing it this way means it works as a stand alone deployment right out the container, but may need some extra work if deployed under another Apache server if you want it to look pretty
(I can rebase this once PR 10 is merged if needed or preferred)

Place static files assuming standalone use

---

docker/run_container.sh

Adds options to run_container.sh
* re-deploy server image only (easier to keep test data in local testing) 
* deploy locally built images without trying to pull from dockerhub (better for local testing)
These changes don't change the previous behaviour, just add new options

Run container enhancement

---

.travis.yml
api/tests/test_cloud_record_summary.py
api/views/CloudRecordSummaryView.py

Adds test cases for a GET requests, checking 200, 400, 401 and 403 responses.
- also moves some of the logging into helper functions
- CloudSummaryRecordView changes so that methods return values rather than raising exceptions to make testing easier (i.e. returning None from method is mockable more easily). The moving of the logging simplifies the top level method get()

Add more test cases for GET requests

---

apel_rest/settings.py
api/tests/test_cloud_record.py
api/views/CloudRecordView.py

Changes to api/views/CloudRecordView.py 
* Factor out the external call (to get the list of providers) to single method
* Move `enumerate(site_json['rows']` into `try...except` becaue if external call fails it throws an exception
Also adds new tests for
* Successful POST
* Unauthorized POST
* Unauthenticated POST
* External call fails during POST

Factor out the external call (to get the list of providers) to single method

---

apel_rest/settings.py
api/views/CloudRecordSummaryView.py
api/views/CloudRecordView.py

Removes the method level getLogger() calls, uses class level logging instead.
- also removes timestamp from the verbose format as it appear twice in log output.

Removal of the method level getLogger() calls

---

api/tests/test_cloud_record.py
api/views/CloudRecordView.py

- An 'enumerate' section and a 'hostname extraction' section
- Because they should be handled separately
- If JSON is of the wrong format it now returns False
- If a site, in the correctly formatted JSON, doesn't define a hostname, it will now continue extracting hostnames.
Extended Explanation:
Change to the method that authorizes a provider to POST based on DN/hostname.
This method has requires an external api call to return the list of valid providers. If the returned JSON is not in the expected format this method could throw a KeyError in two different ways. 
First, if the returned JSON is not of the form `{"total_rows":744,"offset":703,"rows":[...list of JSON objects representing sites...]}`, then `enumerate(providers['rows'])` could throw a KeyError. In this case, the method should …

Split _signer _is_valid try..catch section into two sections

---

apel_rest/urls.py
api/tests/test_cloud_record.py
api/tests/test_cloud_record_summary.py

Adds the name parameter to the `urlpatterns` to allow [reverse URL resolution](https://docs.djangoproject.com/en/1.10/topics/http/urls/#reverse-resolution-of-urls) by the test cases.
- Tests refer to urls by a name, rather than the actual url
- So if the urls change, only the `urls.py` file needs to be changed

Removes hardcoded urls from test cases

---

doc/user.md

Current user documentation indicates how to access the summaries, but does not give an indication on what will be returned. As such an example output has been added.
Also added missing / removed unneeded words in the 'Supported key=value pairs' section

Add example output of GET requests to documentation

---

.travis.yml
api/tests/test_small_scripts.py

Add _simple_ test cases for the small scripts so that they're at least run with the tests and we'll pick up any _simple_ problems later on. Emphasis on the simple. (Also it was bugging me that you've been hovering at just under 90% coverage for while. 😛  )
Also, update Travis file to:
- Remove allowed failure of Python 2.7 tests as this version should be checked.
- Update Python 3 test to latest version.

Add tests and update Travis file

---

apel_rest/settings.py
api/views/CloudRecordSummaryView.py

remove the hard coded URL from source code in favour of a configuration option

Allow for the Identity and Access Management (IAM) URL to be set in settings.py

---

docker/Dockerfile
docker/run_on_entry.sh

On start-up, before starting the apache server, the docker image will now pull down the latest certificate revocation lists for the trust bundle.
They are then updated periodically (every 6 hours).
This way, if a certificate is revoked at a later date, it will no longer be able to be used to access the interface.

Add Fetching of Certificate Revokation Lists to Docker build

---

apel_rest/settings.py
api/tests/test_cloud_record.py
api/views/CloudRecordView.py
doc/service_reference_card.md

POST endpoint will now AuthZ requests in the following order
- if the DN has been explicitly banned (added to `BANNED_FROM_POST`), do not allow.
- if the hostname in the DN is a listed provider, allow
- if the DN has been explicitly set to be allowed (added to `ALLOW_FOR_POST`), then allow
Test cases have been added to check this behaviour.
Banning users has been documented in the service reference card.

Add the ability to locally ban/allow POST requests

---

api/tests/test_cloud_record_summary.py
api/views/CloudRecordSummaryView.py

This change makes the code responsible for filtering returned values slightly more readable, as it doesn't use terms like column and index, but rather key, value pairs
It also improves the readability of the test case, as the mocked data is a dictionary, rather than separate lists of headers and a nested list of data

Replace default cursor object with a DictCursor

---

apel_rest/settings.py
api/tests/test_cloud_record_summary.py
api/views/CloudRecordSummaryView.py
doc/user.md

As requested by the Indigo SLA/QoS tool (which access the summaries), so that if the Indigo group information does not propagate fully to the provider, the SLA/QoS tool can determine usage per user and assign that to a group via a mapping they can access/maintain.
This PR:
- exposes the field `GlobalUserName` in the returned summaries (by adding it to `RETURN_HEADERS`)
- adds the ability to query the summaries via `GlobalUserName`, 
i.e. `/api/vi/cloud/summary?user=someuser`
- adds `GlobalUserName` to the expected responses of test cases
- updates user documentation to explain the `user` key=value pair and updated example returned summaries.

Adds ability to query summaries by GlobalUserName

---

doc/user.md
scripts/sender.py

A standalone send via REST script based off the prototype SSM REST methods.
Using this replaces the need for using the SSM prototype in Indigo.

Add a simple script to sender to the APEL REST interface

---

api/tests/test_cloud_record_summary.py
docker/Dockerfile
schemas/cloud.sql
scripts/update_schema.sql

Allows the APEL REST docker image to support Cloud Usage Record v0.4
- Adds Cloud Usage Record v0.4 fields to the Indigo `cloud.sql` schema
- Adds `CloudComputeServiceID` dummy data a test case that interacts with `VCloudSumaries`.
As the view now uses `CloudComputeServiceID` to perform the join.
- Uses a modified version of the APEL `update_schema.sql` file to
upgrade existing instances of APEL REST for Indigo
- `PublicIPCount` has been left in the v0.4 Cloud Summaries, as this is a feature
Indigo have been pushing for.
- The Dockerfile has been updated to pull in the APEL 1.6.0-1 RPM, and the build tested
- no (non test) python changes required, as the code to handle v0.4 is 
in the new APEL RPM

Upgrade to APEL 1.6.0

---

api/tests/test_cloud_record.py

This removes the repeated
`response = test_client.post(url, MESSAGE, content_type="text/plain", HTTP_EMPA_ID="Test Process",  SSL_CLIENT_S_DN=example_dn)`
and replace them with a function call e.g.:
`self._make_record_post(MESSAGE, 202, dn=example_dn)`
This will also make it easier to test edge cases of a successful POST in future

Refactor test POST code into a single method that is called several times

---

scripts/sender.py

This was causing messages to have new lines replaced with `\n` and wrapped in `"`. It was thought the json.dumps step was needed, but that is not the case.

Replace `json.dumps(data)` with `data`

---

.travis.yml
requirements.txt
test_requirements.txt

[coveralls 1.2.0](https://pypi.python.org/pypi/coveralls/1.2.0) has been released. This has seemingly introduced a new dependency on a non python package `libffi`. This package was not being installed into the Docker image during the Docker Hub [builds](https://hub.docker.com/r/gregcorbett/rest/builds/bkdzdrcc4rnbn9zpxrcrgcg/), as such the builds were failing.
To fix the Docker builds, this PR splits `requirements.txt` into:
- `requirements.txt` - requirements used at run time
- `test_requirements.txt` - requirements used for testing only
This means the Docker build does not try and install `coveralls` (or any future testing only dependencies) into the Docker image.
In order to continue to allow the test to pass on travis, `.travis.yml` has been changed to install both `requirements.txt` …

Remove coveralls from the Docker Image

---

api/tests/__init__.py
api/tests/test_cloud_record_helper.py
api/tests/test_cloud_record_post.py

`test_cloud_record_helper.py` tests the underlying helper methods.
- this file contains a new test `test_signer_is_valid`, which only tests the `_signer_is_valid`
`test_cloud_record_post.py` tests the overall `post` method by making POST requests
- this file is essentially the old `test_cloud_record.py`
Splitting the two type of test makes the files more manageable/smaller. The additional test may catch cases when a POST request is made, `_signer_is_valid` fails, but the POST request carries on to fail in the way the test was expected, thus not causing a test failure.
I have also moved class variables to the `__init__.py` file, as `PROVIDERS` was now being defined twice in two different classes (and I felt like MESSAGE could also be moved encase future tests want to make use of it.)

Split testing of CloudRecordView into two files

---

api/tests/test_cloud_record_summary_get.py
api/tests/test_cloud_record_summary_helper.py

Split test_cloud_record_summary.py into two files. 
- Tests in `api/tests/test_cloud_record_summary_get.py`  make `GET` requests and looks at the response for test pass/fail.
- Tests in `api/tests/test_cloud_record_summary_helper.py` test helper methods and looks at the result of those methods to determine test pass/fail (note: some of these do make GET request objects, as the helper methods expect take the whole request as input, but don't actually make GET requests )
Remove test_request_to_token_fail
- The functionality of making a GET request with a malformed/missing AuthN header is already tested in `api/tests/test_cloud_record_summary_get.py`. 
- New functionality has been added to test_request_to_token to unit test the underlying method
Adds a helper method to make GET  requests …

Refactor testing of CloudRecordSummaryView

---

Dockerfile
conf/apel_rest_api.conf
conf/ssl.conf
docker/run_on_entry.sh

The Indigo SQA team have requested the Docker image be upgraded to Centos7. This PR does that.
It does so in the 'easiest' way, resulting in minimal changes, as the next release is the last release of the project.
`systemd` is not present in the Centos7 docker images, so we can't start 'services'. This solution runs `httpd`, `crond` and `atd` as processes and changes the `fetch-crl-cron` job to not be dependent on a service, which is the default behaviour of `fetch-crl-cron` so previously we didn't have to change the cron job.
`httpd` for Centos7 is a newer version than for Centos6 and requires some changes (as per [Upgrading to 2.4 from 2.2](https://httpd.apache.org/docs/current/upgrading.html)).
- change `Allow for all` to `Require all granted`
- `SSLMutex` has been replaced with the …

Upgrade base Docker image to Centos7

---

apel_rest/settings.py
api/tests/test_cloud_record_summary_get.py
api/tests/test_token_checker.py
api/utils/TokenChecker.py
api/utils/__init__.py
api/views/CloudRecordSummaryView.py
docker/run_on_entry.sh
requirements.txt
yaml/apel_rest_interface.env

As per Indigo IAM best practices:
- Tokens will now be introspected for temporal validaty (issued in the past, expires in the future) and that they are from one of possibly many 'trusted' IAM as defined by the `IAM_HOSTNAME_LIST` in `apel_rest/settings.py` file.
- Tokens are verified by getting the public key of its trusted issuer.
- Tokens are now cached for 5 minutes on a successful request to reduce load on the IAM.
`docker.run_on_entry.py` and `yaml/apel_rest_interface` have also been changed to allow deployment with support for multiple IAMs
Tests have also been added for the `TokenChecker` class and existing `CloudRecordSummaryView` tests have had this new functionality mocked away as they use garbage tokens.

Add Token introspection and Caching

---

docker/README.md

The instructions in `docker/README.md` are outdated and have been superseded by `README.md`. 
This PR changes `docker/README.md` to refer to `README.md` rather than duplicate documentation

Update docker/README.md to refer to main README.md
